[[shades]]
name = "vibrance"
default = true

[[shades]]
name = "blue-light-filter"
start_time = 19:00:00
end_time = 06:00:00

[[shades]]
name = "color-filter"
[shades.config]
type = "protanopia" # "protanopia", "deuteranopia", "tritanopia"
intensity = 1.0     # 0.0 - 1.0
